# Generated by Django 6.0.7 on 2026-08-05 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeerProfile',
            new_name='EmployerProfile',
        ),
    ]
