# Generated by Django 6.0.7 on 2026-08-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-reported_at'], 'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
        migrations.AlterField(
            model_name='report',
            name='report_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_reason',
            field=models.CharField(choices=[('Spam', 'Spam'), ('Fake Job', 'Fake Job'), ('Scam', 'Scam'), ('Misleading Information', 'Misleading Information'), ('Duplicate', 'Duplicate'), ('Offensive Content', 'Offensive Content'), ('Expired Job', 'Expired Job'), ('Other', 'Other')], max_length=50),
        ),
    ]
