# Generated by Django 6.1 on 2026-08-11 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('moderator', '0002_alter_report_reviewed_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='job_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='jobs.jobposting'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['Pending', 'Under Review'])), fields=('job_post', 'reported_by'), name='one_open_report_per_user_per_job'),
        ),
    ]
