# Generated by Django 6.1 on 2026-08-12 01:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0003_report_job_post_alter_report_reviewed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='report',
            name='one_open_report_per_user_per_job',
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['Pending', 'Under Review'])), fields=('reported_by',), name='one_open_report_per_user_per_job'),
        ),
        migrations.RemoveField(
            model_name='report',
            name='job_post',
        ),
    ]
