# Generated by Django 6.1 on 2026-08-12 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('moderator', '0005_alter_report_reported_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='report',
            name='one_open_report_per_user_per_job',
        ),
        migrations.AddField(
            model_name='report',
            name='reported_job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='jobs.jobposting'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='report_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_reason',
            field=models.CharField(choices=[('Spam', 'Spam'), ('Fake Job', 'Fake Job'), ('Scam', 'Scam'), ('Misleading Information', 'Misleading Information'), ('Duplicate', 'Duplicate'), ('Offensive Content', 'Offensive Content'), ('Expired Job', 'Expired Job'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['Pending', 'Under Review'])), fields=('reported_by', 'reported_job'), name='one_open_report_per_user_per_job'),
        ),
    ]
