# Generated by Django 6.1 on 2026-08-18 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0008_delete_jobmoderation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='report',
            name='one_open_report_per_user_per_job',
        ),
    ]
