# Generated by Django 6.0 on 2026-08-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_email_verified_emailotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('emv', 'Email Verification'), ('prv', 'Password Verification'), ('dav', 'delete Verification')], max_length=3),
        ),
    ]
