# Generated by Django 6.0 on 2026-08-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_emailotp_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('emv', 'Email Verification'), ('prv', 'Password Verification'), ('cev', 'Change Email Verification'), ('dav', 'delete Verification')], max_length=3),
        ),
    ]
