# Generated by Django 6.0.7 on 2026-08-21 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='applications.application')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_notes', to='accounts.employerprofile')),
            ],
            options={
                'verbose_name': 'Application Note',
                'verbose_name_plural': 'Application Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
